"""add data fields to ingredients table

Revision ID: 3c4d66315136
Revises: 71acd12e9f55
Create Date: 2020-03-01 13:49:14.684275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4d66315136'
down_revision = '71acd12e9f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('availability', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('availability_withperk', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('can_grow', sa.Boolean(), nullable=True))
    op.add_column('ingredients', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('ingredients', sa.Column('obtaining', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'obtaining')
    op.drop_column('ingredients', 'image_url')
    op.drop_column('ingredients', 'can_grow')
    op.drop_column('ingredients', 'availability_withperk')
    op.drop_column('ingredients', 'availability')
    # ### end Alembic commands ###
