"""initial migration

Revision ID: 8f6e50c54504
Revises: 
Create Date: 2020-03-11 22:42:13.577152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6e50c54504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('base_cost', sa.Float(), nullable=True),
    sa.Column('base_mag', sa.Integer(), nullable=True),
    sa.Column('base_duration', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('is_dlc', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('obtaining', sa.String(length=255), nullable=True),
    sa.Column('effect_id1', sa.Integer(), nullable=True),
    sa.Column('effect_id2', sa.Integer(), nullable=True),
    sa.Column('effect_id3', sa.Integer(), nullable=True),
    sa.Column('effect_id4', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.Column('availability_perk', sa.Integer(), nullable=True),
    sa.Column('can_grow', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['availability'], ['availability.id'], ),
    sa.ForeignKeyConstraint(['availability_perk'], ['availability.id'], ),
    sa.ForeignKeyConstraint(['effect_id1'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['effect_id2'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['effect_id3'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['effect_id4'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('games')
    op.drop_table('effects')
    op.drop_table('availability')
    # ### end Alembic commands ###
